// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compensacoes_bancarias.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countCompensacoesByStatus = `-- name: CountCompensacoesByStatus :one
SELECT COUNT(*) FROM compensacoes_bancarias
WHERE tenant_id = $1 AND status = $2
`

type CountCompensacoesByStatusParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   *string     `json:"status"`
}

func (q *Queries) CountCompensacoesByStatus(ctx context.Context, arg CountCompensacoesByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompensacoesByStatus, arg.TenantID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompensacoesByTenant = `-- name: CountCompensacoesByTenant :one
SELECT COUNT(*) FROM compensacoes_bancarias
WHERE tenant_id = $1
`

func (q *Queries) CountCompensacoesByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompensacoesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompensacaoBancaria = `-- name: CreateCompensacaoBancaria :one
INSERT INTO compensacoes_bancarias (
    tenant_id,
    receita_id,
    data_transacao,
    data_compensacao,
    data_compensado,
    valor_bruto,
    taxa_percentual,
    taxa_fixa,
    valor_liquido,
    meio_pagamento_id,
    d_mais,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, tenant_id, receita_id, data_transacao, data_compensacao, data_compensado, valor_bruto, taxa_percentual, taxa_fixa, valor_liquido, meio_pagamento_id, d_mais, status, criado_em, atualizado_em
`

type CreateCompensacaoBancariaParams struct {
	TenantID        pgtype.UUID     `json:"tenant_id"`
	ReceitaID       pgtype.UUID     `json:"receita_id"`
	DataTransacao   pgtype.Date     `json:"data_transacao"`
	DataCompensacao pgtype.Date     `json:"data_compensacao"`
	DataCompensado  pgtype.Date     `json:"data_compensado"`
	ValorBruto      decimal.Decimal `json:"valor_bruto"`
	TaxaPercentual  pgtype.Numeric  `json:"taxa_percentual"`
	TaxaFixa        pgtype.Numeric  `json:"taxa_fixa"`
	ValorLiquido    decimal.Decimal `json:"valor_liquido"`
	MeioPagamentoID pgtype.UUID     `json:"meio_pagamento_id"`
	DMais           int32           `json:"d_mais"`
	Status          *string         `json:"status"`
}

func (q *Queries) CreateCompensacaoBancaria(ctx context.Context, arg CreateCompensacaoBancariaParams) (CompensacoesBancaria, error) {
	row := q.db.QueryRow(ctx, createCompensacaoBancaria,
		arg.TenantID,
		arg.ReceitaID,
		arg.DataTransacao,
		arg.DataCompensacao,
		arg.DataCompensado,
		arg.ValorBruto,
		arg.TaxaPercentual,
		arg.TaxaFixa,
		arg.ValorLiquido,
		arg.MeioPagamentoID,
		arg.DMais,
		arg.Status,
	)
	var i CompensacoesBancaria
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReceitaID,
		&i.DataTransacao,
		&i.DataCompensacao,
		&i.DataCompensado,
		&i.ValorBruto,
		&i.TaxaPercentual,
		&i.TaxaFixa,
		&i.ValorLiquido,
		&i.MeioPagamentoID,
		&i.DMais,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const deleteCompensacaoBancaria = `-- name: DeleteCompensacaoBancaria :exec
DELETE FROM compensacoes_bancarias
WHERE id = $1 AND tenant_id = $2
`

type DeleteCompensacaoBancariaParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteCompensacaoBancaria(ctx context.Context, arg DeleteCompensacaoBancariaParams) error {
	_, err := q.db.Exec(ctx, deleteCompensacaoBancaria, arg.ID, arg.TenantID)
	return err
}

const getCompensacaoBancariaByID = `-- name: GetCompensacaoBancariaByID :one
SELECT id, tenant_id, receita_id, data_transacao, data_compensacao, data_compensado, valor_bruto, taxa_percentual, taxa_fixa, valor_liquido, meio_pagamento_id, d_mais, status, criado_em, atualizado_em FROM compensacoes_bancarias
WHERE id = $1 AND tenant_id = $2
`

type GetCompensacaoBancariaByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetCompensacaoBancariaByID(ctx context.Context, arg GetCompensacaoBancariaByIDParams) (CompensacoesBancaria, error) {
	row := q.db.QueryRow(ctx, getCompensacaoBancariaByID, arg.ID, arg.TenantID)
	var i CompensacoesBancaria
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReceitaID,
		&i.DataTransacao,
		&i.DataCompensacao,
		&i.DataCompensado,
		&i.ValorBruto,
		&i.TaxaPercentual,
		&i.TaxaFixa,
		&i.ValorLiquido,
		&i.MeioPagamentoID,
		&i.DMais,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listCompensacoesBancariasByTenant = `-- name: ListCompensacoesBancariasByTenant :many
SELECT id, tenant_id, receita_id, data_transacao, data_compensacao, data_compensado, valor_bruto, taxa_percentual, taxa_fixa, valor_liquido, meio_pagamento_id, d_mais, status, criado_em, atualizado_em FROM compensacoes_bancarias
WHERE tenant_id = $1
ORDER BY data_compensacao DESC
LIMIT $2 OFFSET $3
`

type ListCompensacoesBancariasByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListCompensacoesBancariasByTenant(ctx context.Context, arg ListCompensacoesBancariasByTenantParams) ([]CompensacoesBancaria, error) {
	rows, err := q.db.Query(ctx, listCompensacoesBancariasByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompensacoesBancaria{}
	for rows.Next() {
		var i CompensacoesBancaria
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ReceitaID,
			&i.DataTransacao,
			&i.DataCompensacao,
			&i.DataCompensado,
			&i.ValorBruto,
			&i.TaxaPercentual,
			&i.TaxaFixa,
			&i.ValorLiquido,
			&i.MeioPagamentoID,
			&i.DMais,
			&i.Status,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompensacoesByDataCompensacao = `-- name: ListCompensacoesByDataCompensacao :many
SELECT id, tenant_id, receita_id, data_transacao, data_compensacao, data_compensado, valor_bruto, taxa_percentual, taxa_fixa, valor_liquido, meio_pagamento_id, d_mais, status, criado_em, atualizado_em FROM compensacoes_bancarias
WHERE tenant_id = $1
  AND data_compensacao >= $2
  AND data_compensacao <= $3
ORDER BY data_compensacao ASC
`

type ListCompensacoesByDataCompensacaoParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	DataCompensacao   pgtype.Date `json:"data_compensacao"`
	DataCompensacao_2 pgtype.Date `json:"data_compensacao_2"`
}

func (q *Queries) ListCompensacoesByDataCompensacao(ctx context.Context, arg ListCompensacoesByDataCompensacaoParams) ([]CompensacoesBancaria, error) {
	rows, err := q.db.Query(ctx, listCompensacoesByDataCompensacao, arg.TenantID, arg.DataCompensacao, arg.DataCompensacao_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompensacoesBancaria{}
	for rows.Next() {
		var i CompensacoesBancaria
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ReceitaID,
			&i.DataTransacao,
			&i.DataCompensacao,
			&i.DataCompensado,
			&i.ValorBruto,
			&i.TaxaPercentual,
			&i.TaxaFixa,
			&i.ValorLiquido,
			&i.MeioPagamentoID,
			&i.DMais,
			&i.Status,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompensacoesByReceita = `-- name: ListCompensacoesByReceita :many
SELECT id, tenant_id, receita_id, data_transacao, data_compensacao, data_compensado, valor_bruto, taxa_percentual, taxa_fixa, valor_liquido, meio_pagamento_id, d_mais, status, criado_em, atualizado_em FROM compensacoes_bancarias
WHERE tenant_id = $1 AND receita_id = $2
ORDER BY data_compensacao DESC
`

type ListCompensacoesByReceitaParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ReceitaID pgtype.UUID `json:"receita_id"`
}

func (q *Queries) ListCompensacoesByReceita(ctx context.Context, arg ListCompensacoesByReceitaParams) ([]CompensacoesBancaria, error) {
	rows, err := q.db.Query(ctx, listCompensacoesByReceita, arg.TenantID, arg.ReceitaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompensacoesBancaria{}
	for rows.Next() {
		var i CompensacoesBancaria
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ReceitaID,
			&i.DataTransacao,
			&i.DataCompensacao,
			&i.DataCompensado,
			&i.ValorBruto,
			&i.TaxaPercentual,
			&i.TaxaFixa,
			&i.ValorLiquido,
			&i.MeioPagamentoID,
			&i.DMais,
			&i.Status,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompensacoesByStatus = `-- name: ListCompensacoesByStatus :many
SELECT id, tenant_id, receita_id, data_transacao, data_compensacao, data_compensado, valor_bruto, taxa_percentual, taxa_fixa, valor_liquido, meio_pagamento_id, d_mais, status, criado_em, atualizado_em FROM compensacoes_bancarias
WHERE tenant_id = $1 AND status = $2
ORDER BY data_compensacao DESC
LIMIT $3 OFFSET $4
`

type ListCompensacoesByStatusParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Status   *string     `json:"status"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListCompensacoesByStatus(ctx context.Context, arg ListCompensacoesByStatusParams) ([]CompensacoesBancaria, error) {
	rows, err := q.db.Query(ctx, listCompensacoesByStatus,
		arg.TenantID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompensacoesBancaria{}
	for rows.Next() {
		var i CompensacoesBancaria
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ReceitaID,
			&i.DataTransacao,
			&i.DataCompensacao,
			&i.DataCompensado,
			&i.ValorBruto,
			&i.TaxaPercentual,
			&i.TaxaFixa,
			&i.ValorLiquido,
			&i.MeioPagamentoID,
			&i.DMais,
			&i.Status,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarComoCompensado = `-- name: MarcarComoCompensado :one
UPDATE compensacoes_bancarias
SET
    status = 'COMPENSADO',
    data_compensado = $3,
    atualizado_em = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, receita_id, data_transacao, data_compensacao, data_compensado, valor_bruto, taxa_percentual, taxa_fixa, valor_liquido, meio_pagamento_id, d_mais, status, criado_em, atualizado_em
`

type MarcarComoCompensadoParams struct {
	ID             pgtype.UUID `json:"id"`
	TenantID       pgtype.UUID `json:"tenant_id"`
	DataCompensado pgtype.Date `json:"data_compensado"`
}

func (q *Queries) MarcarComoCompensado(ctx context.Context, arg MarcarComoCompensadoParams) (CompensacoesBancaria, error) {
	row := q.db.QueryRow(ctx, marcarComoCompensado, arg.ID, arg.TenantID, arg.DataCompensado)
	var i CompensacoesBancaria
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReceitaID,
		&i.DataTransacao,
		&i.DataCompensacao,
		&i.DataCompensado,
		&i.ValorBruto,
		&i.TaxaPercentual,
		&i.TaxaFixa,
		&i.ValorLiquido,
		&i.MeioPagamentoID,
		&i.DMais,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const sumValorLiquidoByPeriod = `-- name: SumValorLiquidoByPeriod :one
SELECT
    COALESCE(SUM(valor_liquido), 0) as total_liquido
FROM compensacoes_bancarias
WHERE tenant_id = $1
  AND data_compensacao >= $2
  AND data_compensacao <= $3
  AND status IN ('COMPENSADO', 'CONFIRMADO')
`

type SumValorLiquidoByPeriodParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	DataCompensacao   pgtype.Date `json:"data_compensacao"`
	DataCompensacao_2 pgtype.Date `json:"data_compensacao_2"`
}

func (q *Queries) SumValorLiquidoByPeriod(ctx context.Context, arg SumValorLiquidoByPeriodParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumValorLiquidoByPeriod, arg.TenantID, arg.DataCompensacao, arg.DataCompensacao_2)
	var total_liquido interface{}
	err := row.Scan(&total_liquido)
	return total_liquido, err
}

const updateCompensacaoBancaria = `-- name: UpdateCompensacaoBancaria :one
UPDATE compensacoes_bancarias
SET
    data_compensacao = $3,
    data_compensado = $4,
    valor_bruto = $5,
    taxa_percentual = $6,
    taxa_fixa = $7,
    valor_liquido = $8,
    status = $9,
    atualizado_em = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, receita_id, data_transacao, data_compensacao, data_compensado, valor_bruto, taxa_percentual, taxa_fixa, valor_liquido, meio_pagamento_id, d_mais, status, criado_em, atualizado_em
`

type UpdateCompensacaoBancariaParams struct {
	ID              pgtype.UUID     `json:"id"`
	TenantID        pgtype.UUID     `json:"tenant_id"`
	DataCompensacao pgtype.Date     `json:"data_compensacao"`
	DataCompensado  pgtype.Date     `json:"data_compensado"`
	ValorBruto      decimal.Decimal `json:"valor_bruto"`
	TaxaPercentual  pgtype.Numeric  `json:"taxa_percentual"`
	TaxaFixa        pgtype.Numeric  `json:"taxa_fixa"`
	ValorLiquido    decimal.Decimal `json:"valor_liquido"`
	Status          *string         `json:"status"`
}

func (q *Queries) UpdateCompensacaoBancaria(ctx context.Context, arg UpdateCompensacaoBancariaParams) (CompensacoesBancaria, error) {
	row := q.db.QueryRow(ctx, updateCompensacaoBancaria,
		arg.ID,
		arg.TenantID,
		arg.DataCompensacao,
		arg.DataCompensado,
		arg.ValorBruto,
		arg.TaxaPercentual,
		arg.TaxaFixa,
		arg.ValorLiquido,
		arg.Status,
	)
	var i CompensacoesBancaria
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ReceitaID,
		&i.DataTransacao,
		&i.DataCompensacao,
		&i.DataCompensado,
		&i.ValorBruto,
		&i.TaxaPercentual,
		&i.TaxaFixa,
		&i.ValorLiquido,
		&i.MeioPagamentoID,
		&i.DMais,
		&i.Status,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}
