// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dre_mensal.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const avgMargemBrutaByPeriod = `-- name: AvgMargemBrutaByPeriod :one
SELECT
    COALESCE(AVG(margem_bruta), 0) as media_margem_bruta
FROM dre_mensal
WHERE tenant_id = $1
  AND mes_ano >= $2
  AND mes_ano <= $3
`

type AvgMargemBrutaByPeriodParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	MesAno   string      `json:"mes_ano"`
	MesAno_2 string      `json:"mes_ano_2"`
}

func (q *Queries) AvgMargemBrutaByPeriod(ctx context.Context, arg AvgMargemBrutaByPeriodParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, avgMargemBrutaByPeriod, arg.TenantID, arg.MesAno, arg.MesAno_2)
	var media_margem_bruta interface{}
	err := row.Scan(&media_margem_bruta)
	return media_margem_bruta, err
}

const avgMargemOperacionalByPeriod = `-- name: AvgMargemOperacionalByPeriod :one
SELECT
    COALESCE(AVG(margem_operacional), 0) as media_margem_operacional
FROM dre_mensal
WHERE tenant_id = $1
  AND mes_ano >= $2
  AND mes_ano <= $3
`

type AvgMargemOperacionalByPeriodParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	MesAno   string      `json:"mes_ano"`
	MesAno_2 string      `json:"mes_ano_2"`
}

func (q *Queries) AvgMargemOperacionalByPeriod(ctx context.Context, arg AvgMargemOperacionalByPeriodParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, avgMargemOperacionalByPeriod, arg.TenantID, arg.MesAno, arg.MesAno_2)
	var media_margem_operacional interface{}
	err := row.Scan(&media_margem_operacional)
	return media_margem_operacional, err
}

const countDREMensalByTenant = `-- name: CountDREMensalByTenant :one
SELECT COUNT(*) FROM dre_mensal
WHERE tenant_id = $1
`

func (q *Queries) CountDREMensalByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDREMensalByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDREMensal = `-- name: CreateDREMensal :one
INSERT INTO dre_mensal (
    tenant_id,
    mes_ano,
    receita_servicos,
    receita_produtos,
    receita_planos,
    receita_total,
    custo_comissoes,
    custo_insumos,
    custo_variavel_total,
    despesa_fixa,
    despesa_variavel,
    despesa_total,
    resultado_bruto,
    resultado_operacional,
    margem_bruta,
    margem_operacional,
    lucro_liquido,
    processado_em
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
) RETURNING id, tenant_id, mes_ano, receita_servicos, receita_produtos, receita_planos, receita_total, custo_comissoes, custo_insumos, custo_variavel_total, despesa_fixa, despesa_variavel, despesa_total, resultado_bruto, resultado_operacional, margem_bruta, margem_operacional, lucro_liquido, processado_em, criado_em, atualizado_em
`

type CreateDREMensalParams struct {
	TenantID             pgtype.UUID        `json:"tenant_id"`
	MesAno               string             `json:"mes_ano"`
	ReceitaServicos      pgtype.Numeric     `json:"receita_servicos"`
	ReceitaProdutos      pgtype.Numeric     `json:"receita_produtos"`
	ReceitaPlanos        pgtype.Numeric     `json:"receita_planos"`
	ReceitaTotal         pgtype.Numeric     `json:"receita_total"`
	CustoComissoes       pgtype.Numeric     `json:"custo_comissoes"`
	CustoInsumos         pgtype.Numeric     `json:"custo_insumos"`
	CustoVariavelTotal   pgtype.Numeric     `json:"custo_variavel_total"`
	DespesaFixa          pgtype.Numeric     `json:"despesa_fixa"`
	DespesaVariavel      pgtype.Numeric     `json:"despesa_variavel"`
	DespesaTotal         pgtype.Numeric     `json:"despesa_total"`
	ResultadoBruto       pgtype.Numeric     `json:"resultado_bruto"`
	ResultadoOperacional pgtype.Numeric     `json:"resultado_operacional"`
	MargemBruta          pgtype.Numeric     `json:"margem_bruta"`
	MargemOperacional    pgtype.Numeric     `json:"margem_operacional"`
	LucroLiquido         pgtype.Numeric     `json:"lucro_liquido"`
	ProcessadoEm         pgtype.Timestamptz `json:"processado_em"`
}

func (q *Queries) CreateDREMensal(ctx context.Context, arg CreateDREMensalParams) (DreMensal, error) {
	row := q.db.QueryRow(ctx, createDREMensal,
		arg.TenantID,
		arg.MesAno,
		arg.ReceitaServicos,
		arg.ReceitaProdutos,
		arg.ReceitaPlanos,
		arg.ReceitaTotal,
		arg.CustoComissoes,
		arg.CustoInsumos,
		arg.CustoVariavelTotal,
		arg.DespesaFixa,
		arg.DespesaVariavel,
		arg.DespesaTotal,
		arg.ResultadoBruto,
		arg.ResultadoOperacional,
		arg.MargemBruta,
		arg.MargemOperacional,
		arg.LucroLiquido,
		arg.ProcessadoEm,
	)
	var i DreMensal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MesAno,
		&i.ReceitaServicos,
		&i.ReceitaProdutos,
		&i.ReceitaPlanos,
		&i.ReceitaTotal,
		&i.CustoComissoes,
		&i.CustoInsumos,
		&i.CustoVariavelTotal,
		&i.DespesaFixa,
		&i.DespesaVariavel,
		&i.DespesaTotal,
		&i.ResultadoBruto,
		&i.ResultadoOperacional,
		&i.MargemBruta,
		&i.MargemOperacional,
		&i.LucroLiquido,
		&i.ProcessadoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const deleteDREMensal = `-- name: DeleteDREMensal :exec
DELETE FROM dre_mensal
WHERE id = $1 AND tenant_id = $2
`

type DeleteDREMensalParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteDREMensal(ctx context.Context, arg DeleteDREMensalParams) error {
	_, err := q.db.Exec(ctx, deleteDREMensal, arg.ID, arg.TenantID)
	return err
}

const getDREMensalByID = `-- name: GetDREMensalByID :one
SELECT id, tenant_id, mes_ano, receita_servicos, receita_produtos, receita_planos, receita_total, custo_comissoes, custo_insumos, custo_variavel_total, despesa_fixa, despesa_variavel, despesa_total, resultado_bruto, resultado_operacional, margem_bruta, margem_operacional, lucro_liquido, processado_em, criado_em, atualizado_em FROM dre_mensal
WHERE id = $1 AND tenant_id = $2
`

type GetDREMensalByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetDREMensalByID(ctx context.Context, arg GetDREMensalByIDParams) (DreMensal, error) {
	row := q.db.QueryRow(ctx, getDREMensalByID, arg.ID, arg.TenantID)
	var i DreMensal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MesAno,
		&i.ReceitaServicos,
		&i.ReceitaProdutos,
		&i.ReceitaPlanos,
		&i.ReceitaTotal,
		&i.CustoComissoes,
		&i.CustoInsumos,
		&i.CustoVariavelTotal,
		&i.DespesaFixa,
		&i.DespesaVariavel,
		&i.DespesaTotal,
		&i.ResultadoBruto,
		&i.ResultadoOperacional,
		&i.MargemBruta,
		&i.MargemOperacional,
		&i.LucroLiquido,
		&i.ProcessadoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getDREMensalByMesAno = `-- name: GetDREMensalByMesAno :one
SELECT id, tenant_id, mes_ano, receita_servicos, receita_produtos, receita_planos, receita_total, custo_comissoes, custo_insumos, custo_variavel_total, despesa_fixa, despesa_variavel, despesa_total, resultado_bruto, resultado_operacional, margem_bruta, margem_operacional, lucro_liquido, processado_em, criado_em, atualizado_em FROM dre_mensal
WHERE tenant_id = $1 AND mes_ano = $2
`

type GetDREMensalByMesAnoParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	MesAno   string      `json:"mes_ano"`
}

func (q *Queries) GetDREMensalByMesAno(ctx context.Context, arg GetDREMensalByMesAnoParams) (DreMensal, error) {
	row := q.db.QueryRow(ctx, getDREMensalByMesAno, arg.TenantID, arg.MesAno)
	var i DreMensal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MesAno,
		&i.ReceitaServicos,
		&i.ReceitaProdutos,
		&i.ReceitaPlanos,
		&i.ReceitaTotal,
		&i.CustoComissoes,
		&i.CustoInsumos,
		&i.CustoVariavelTotal,
		&i.DespesaFixa,
		&i.DespesaVariavel,
		&i.DespesaTotal,
		&i.ResultadoBruto,
		&i.ResultadoOperacional,
		&i.MargemBruta,
		&i.MargemOperacional,
		&i.LucroLiquido,
		&i.ProcessadoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listDREMensalByPeriod = `-- name: ListDREMensalByPeriod :many
SELECT id, tenant_id, mes_ano, receita_servicos, receita_produtos, receita_planos, receita_total, custo_comissoes, custo_insumos, custo_variavel_total, despesa_fixa, despesa_variavel, despesa_total, resultado_bruto, resultado_operacional, margem_bruta, margem_operacional, lucro_liquido, processado_em, criado_em, atualizado_em FROM dre_mensal
WHERE tenant_id = $1
  AND mes_ano >= $2
  AND mes_ano <= $3
ORDER BY mes_ano DESC
`

type ListDREMensalByPeriodParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	MesAno   string      `json:"mes_ano"`
	MesAno_2 string      `json:"mes_ano_2"`
}

func (q *Queries) ListDREMensalByPeriod(ctx context.Context, arg ListDREMensalByPeriodParams) ([]DreMensal, error) {
	rows, err := q.db.Query(ctx, listDREMensalByPeriod, arg.TenantID, arg.MesAno, arg.MesAno_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DreMensal{}
	for rows.Next() {
		var i DreMensal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MesAno,
			&i.ReceitaServicos,
			&i.ReceitaProdutos,
			&i.ReceitaPlanos,
			&i.ReceitaTotal,
			&i.CustoComissoes,
			&i.CustoInsumos,
			&i.CustoVariavelTotal,
			&i.DespesaFixa,
			&i.DespesaVariavel,
			&i.DespesaTotal,
			&i.ResultadoBruto,
			&i.ResultadoOperacional,
			&i.MargemBruta,
			&i.MargemOperacional,
			&i.LucroLiquido,
			&i.ProcessadoEm,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDREMensalByTenant = `-- name: ListDREMensalByTenant :many
SELECT id, tenant_id, mes_ano, receita_servicos, receita_produtos, receita_planos, receita_total, custo_comissoes, custo_insumos, custo_variavel_total, despesa_fixa, despesa_variavel, despesa_total, resultado_bruto, resultado_operacional, margem_bruta, margem_operacional, lucro_liquido, processado_em, criado_em, atualizado_em FROM dre_mensal
WHERE tenant_id = $1
ORDER BY mes_ano DESC
LIMIT $2 OFFSET $3
`

type ListDREMensalByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListDREMensalByTenant(ctx context.Context, arg ListDREMensalByTenantParams) ([]DreMensal, error) {
	rows, err := q.db.Query(ctx, listDREMensalByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DreMensal{}
	for rows.Next() {
		var i DreMensal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MesAno,
			&i.ReceitaServicos,
			&i.ReceitaProdutos,
			&i.ReceitaPlanos,
			&i.ReceitaTotal,
			&i.CustoComissoes,
			&i.CustoInsumos,
			&i.CustoVariavelTotal,
			&i.DespesaFixa,
			&i.DespesaVariavel,
			&i.DespesaTotal,
			&i.ResultadoBruto,
			&i.ResultadoOperacional,
			&i.MargemBruta,
			&i.MargemOperacional,
			&i.LucroLiquido,
			&i.ProcessadoEm,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDespesasByPeriod = `-- name: SumDespesasByPeriod :one
SELECT
    COALESCE(SUM(despesa_total), 0) as total_despesas
FROM dre_mensal
WHERE tenant_id = $1
  AND mes_ano >= $2
  AND mes_ano <= $3
`

type SumDespesasByPeriodParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	MesAno   string      `json:"mes_ano"`
	MesAno_2 string      `json:"mes_ano_2"`
}

func (q *Queries) SumDespesasByPeriod(ctx context.Context, arg SumDespesasByPeriodParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumDespesasByPeriod, arg.TenantID, arg.MesAno, arg.MesAno_2)
	var total_despesas interface{}
	err := row.Scan(&total_despesas)
	return total_despesas, err
}

const sumReceitasByPeriod = `-- name: SumReceitasByPeriod :one
SELECT
    COALESCE(SUM(receita_total), 0) as total_receitas
FROM dre_mensal
WHERE tenant_id = $1
  AND mes_ano >= $2
  AND mes_ano <= $3
`

type SumReceitasByPeriodParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	MesAno   string      `json:"mes_ano"`
	MesAno_2 string      `json:"mes_ano_2"`
}

func (q *Queries) SumReceitasByPeriod(ctx context.Context, arg SumReceitasByPeriodParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumReceitasByPeriod, arg.TenantID, arg.MesAno, arg.MesAno_2)
	var total_receitas interface{}
	err := row.Scan(&total_receitas)
	return total_receitas, err
}

const updateDREMensal = `-- name: UpdateDREMensal :one
UPDATE dre_mensal
SET
    receita_servicos = $3,
    receita_produtos = $4,
    receita_planos = $5,
    receita_total = $6,
    custo_comissoes = $7,
    custo_insumos = $8,
    custo_variavel_total = $9,
    despesa_fixa = $10,
    despesa_variavel = $11,
    despesa_total = $12,
    resultado_bruto = $13,
    resultado_operacional = $14,
    margem_bruta = $15,
    margem_operacional = $16,
    lucro_liquido = $17,
    processado_em = $18,
    atualizado_em = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, mes_ano, receita_servicos, receita_produtos, receita_planos, receita_total, custo_comissoes, custo_insumos, custo_variavel_total, despesa_fixa, despesa_variavel, despesa_total, resultado_bruto, resultado_operacional, margem_bruta, margem_operacional, lucro_liquido, processado_em, criado_em, atualizado_em
`

type UpdateDREMensalParams struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	ReceitaServicos      pgtype.Numeric     `json:"receita_servicos"`
	ReceitaProdutos      pgtype.Numeric     `json:"receita_produtos"`
	ReceitaPlanos        pgtype.Numeric     `json:"receita_planos"`
	ReceitaTotal         pgtype.Numeric     `json:"receita_total"`
	CustoComissoes       pgtype.Numeric     `json:"custo_comissoes"`
	CustoInsumos         pgtype.Numeric     `json:"custo_insumos"`
	CustoVariavelTotal   pgtype.Numeric     `json:"custo_variavel_total"`
	DespesaFixa          pgtype.Numeric     `json:"despesa_fixa"`
	DespesaVariavel      pgtype.Numeric     `json:"despesa_variavel"`
	DespesaTotal         pgtype.Numeric     `json:"despesa_total"`
	ResultadoBruto       pgtype.Numeric     `json:"resultado_bruto"`
	ResultadoOperacional pgtype.Numeric     `json:"resultado_operacional"`
	MargemBruta          pgtype.Numeric     `json:"margem_bruta"`
	MargemOperacional    pgtype.Numeric     `json:"margem_operacional"`
	LucroLiquido         pgtype.Numeric     `json:"lucro_liquido"`
	ProcessadoEm         pgtype.Timestamptz `json:"processado_em"`
}

func (q *Queries) UpdateDREMensal(ctx context.Context, arg UpdateDREMensalParams) (DreMensal, error) {
	row := q.db.QueryRow(ctx, updateDREMensal,
		arg.ID,
		arg.TenantID,
		arg.ReceitaServicos,
		arg.ReceitaProdutos,
		arg.ReceitaPlanos,
		arg.ReceitaTotal,
		arg.CustoComissoes,
		arg.CustoInsumos,
		arg.CustoVariavelTotal,
		arg.DespesaFixa,
		arg.DespesaVariavel,
		arg.DespesaTotal,
		arg.ResultadoBruto,
		arg.ResultadoOperacional,
		arg.MargemBruta,
		arg.MargemOperacional,
		arg.LucroLiquido,
		arg.ProcessadoEm,
	)
	var i DreMensal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MesAno,
		&i.ReceitaServicos,
		&i.ReceitaProdutos,
		&i.ReceitaPlanos,
		&i.ReceitaTotal,
		&i.CustoComissoes,
		&i.CustoInsumos,
		&i.CustoVariavelTotal,
		&i.DespesaFixa,
		&i.DespesaVariavel,
		&i.DespesaTotal,
		&i.ResultadoBruto,
		&i.ResultadoOperacional,
		&i.MargemBruta,
		&i.MargemOperacional,
		&i.LucroLiquido,
		&i.ProcessadoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}
