// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metas_ticket_medio.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countMetasTicketMedioByBarbeiro = `-- name: CountMetasTicketMedioByBarbeiro :one
SELECT COUNT(*) FROM metas_ticket_medio
WHERE tenant_id = $1 AND barbeiro_id = $2
`

type CountMetasTicketMedioByBarbeiroParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	BarbeiroID pgtype.UUID `json:"barbeiro_id"`
}

func (q *Queries) CountMetasTicketMedioByBarbeiro(ctx context.Context, arg CountMetasTicketMedioByBarbeiroParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMetasTicketMedioByBarbeiro, arg.TenantID, arg.BarbeiroID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMetasTicketMedioByTenant = `-- name: CountMetasTicketMedioByTenant :one
SELECT COUNT(*) FROM metas_ticket_medio
WHERE tenant_id = $1
`

func (q *Queries) CountMetasTicketMedioByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMetasTicketMedioByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMetaTicketMedio = `-- name: CreateMetaTicketMedio :one
INSERT INTO metas_ticket_medio (
    tenant_id,
    mes_ano,
    meta_valor,
    tipo,
    barbeiro_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, tenant_id, mes_ano, meta_valor, tipo, barbeiro_id, criado_em, atualizado_em
`

type CreateMetaTicketMedioParams struct {
	TenantID   pgtype.UUID     `json:"tenant_id"`
	MesAno     string          `json:"mes_ano"`
	MetaValor  decimal.Decimal `json:"meta_valor"`
	Tipo       *string         `json:"tipo"`
	BarbeiroID pgtype.UUID     `json:"barbeiro_id"`
}

func (q *Queries) CreateMetaTicketMedio(ctx context.Context, arg CreateMetaTicketMedioParams) (MetasTicketMedio, error) {
	row := q.db.QueryRow(ctx, createMetaTicketMedio,
		arg.TenantID,
		arg.MesAno,
		arg.MetaValor,
		arg.Tipo,
		arg.BarbeiroID,
	)
	var i MetasTicketMedio
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MesAno,
		&i.MetaValor,
		&i.Tipo,
		&i.BarbeiroID,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const deleteMetaTicketMedio = `-- name: DeleteMetaTicketMedio :exec
DELETE FROM metas_ticket_medio
WHERE id = $1 AND tenant_id = $2
`

type DeleteMetaTicketMedioParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteMetaTicketMedio(ctx context.Context, arg DeleteMetaTicketMedioParams) error {
	_, err := q.db.Exec(ctx, deleteMetaTicketMedio, arg.ID, arg.TenantID)
	return err
}

const getMetaTicketMedioBarbeiroByMesAno = `-- name: GetMetaTicketMedioBarbeiroByMesAno :one
SELECT id, tenant_id, mes_ano, meta_valor, tipo, barbeiro_id, criado_em, atualizado_em FROM metas_ticket_medio
WHERE tenant_id = $1
  AND mes_ano = $2
  AND barbeiro_id = $3
  AND tipo = 'BARBEIRO'
`

type GetMetaTicketMedioBarbeiroByMesAnoParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	MesAno     string      `json:"mes_ano"`
	BarbeiroID pgtype.UUID `json:"barbeiro_id"`
}

func (q *Queries) GetMetaTicketMedioBarbeiroByMesAno(ctx context.Context, arg GetMetaTicketMedioBarbeiroByMesAnoParams) (MetasTicketMedio, error) {
	row := q.db.QueryRow(ctx, getMetaTicketMedioBarbeiroByMesAno, arg.TenantID, arg.MesAno, arg.BarbeiroID)
	var i MetasTicketMedio
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MesAno,
		&i.MetaValor,
		&i.Tipo,
		&i.BarbeiroID,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getMetaTicketMedioByID = `-- name: GetMetaTicketMedioByID :one
SELECT id, tenant_id, mes_ano, meta_valor, tipo, barbeiro_id, criado_em, atualizado_em FROM metas_ticket_medio
WHERE id = $1 AND tenant_id = $2
`

type GetMetaTicketMedioByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetMetaTicketMedioByID(ctx context.Context, arg GetMetaTicketMedioByIDParams) (MetasTicketMedio, error) {
	row := q.db.QueryRow(ctx, getMetaTicketMedioByID, arg.ID, arg.TenantID)
	var i MetasTicketMedio
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MesAno,
		&i.MetaValor,
		&i.Tipo,
		&i.BarbeiroID,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getMetaTicketMedioGeralByMesAno = `-- name: GetMetaTicketMedioGeralByMesAno :one
SELECT id, tenant_id, mes_ano, meta_valor, tipo, barbeiro_id, criado_em, atualizado_em FROM metas_ticket_medio
WHERE tenant_id = $1
  AND mes_ano = $2
  AND tipo = 'GERAL'
`

type GetMetaTicketMedioGeralByMesAnoParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	MesAno   string      `json:"mes_ano"`
}

func (q *Queries) GetMetaTicketMedioGeralByMesAno(ctx context.Context, arg GetMetaTicketMedioGeralByMesAnoParams) (MetasTicketMedio, error) {
	row := q.db.QueryRow(ctx, getMetaTicketMedioGeralByMesAno, arg.TenantID, arg.MesAno)
	var i MetasTicketMedio
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MesAno,
		&i.MetaValor,
		&i.Tipo,
		&i.BarbeiroID,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listMetasTicketMedioByBarbeiro = `-- name: ListMetasTicketMedioByBarbeiro :many
SELECT id, tenant_id, mes_ano, meta_valor, tipo, barbeiro_id, criado_em, atualizado_em FROM metas_ticket_medio
WHERE tenant_id = $1
  AND barbeiro_id = $2
  AND tipo = 'BARBEIRO'
ORDER BY mes_ano DESC
LIMIT $3 OFFSET $4
`

type ListMetasTicketMedioByBarbeiroParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	BarbeiroID pgtype.UUID `json:"barbeiro_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListMetasTicketMedioByBarbeiro(ctx context.Context, arg ListMetasTicketMedioByBarbeiroParams) ([]MetasTicketMedio, error) {
	rows, err := q.db.Query(ctx, listMetasTicketMedioByBarbeiro,
		arg.TenantID,
		arg.BarbeiroID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetasTicketMedio{}
	for rows.Next() {
		var i MetasTicketMedio
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MesAno,
			&i.MetaValor,
			&i.Tipo,
			&i.BarbeiroID,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetasTicketMedioByMesAno = `-- name: ListMetasTicketMedioByMesAno :many
SELECT id, tenant_id, mes_ano, meta_valor, tipo, barbeiro_id, criado_em, atualizado_em FROM metas_ticket_medio
WHERE tenant_id = $1 AND mes_ano = $2
ORDER BY tipo, barbeiro_id
`

type ListMetasTicketMedioByMesAnoParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	MesAno   string      `json:"mes_ano"`
}

func (q *Queries) ListMetasTicketMedioByMesAno(ctx context.Context, arg ListMetasTicketMedioByMesAnoParams) ([]MetasTicketMedio, error) {
	rows, err := q.db.Query(ctx, listMetasTicketMedioByMesAno, arg.TenantID, arg.MesAno)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetasTicketMedio{}
	for rows.Next() {
		var i MetasTicketMedio
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MesAno,
			&i.MetaValor,
			&i.Tipo,
			&i.BarbeiroID,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetasTicketMedioByTenant = `-- name: ListMetasTicketMedioByTenant :many
SELECT id, tenant_id, mes_ano, meta_valor, tipo, barbeiro_id, criado_em, atualizado_em FROM metas_ticket_medio
WHERE tenant_id = $1
ORDER BY mes_ano DESC, tipo, barbeiro_id
LIMIT $2 OFFSET $3
`

type ListMetasTicketMedioByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListMetasTicketMedioByTenant(ctx context.Context, arg ListMetasTicketMedioByTenantParams) ([]MetasTicketMedio, error) {
	rows, err := q.db.Query(ctx, listMetasTicketMedioByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetasTicketMedio{}
	for rows.Next() {
		var i MetasTicketMedio
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MesAno,
			&i.MetaValor,
			&i.Tipo,
			&i.BarbeiroID,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMetaTicketMedio = `-- name: UpdateMetaTicketMedio :one
UPDATE metas_ticket_medio
SET
    meta_valor = $3,
    atualizado_em = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, mes_ano, meta_valor, tipo, barbeiro_id, criado_em, atualizado_em
`

type UpdateMetaTicketMedioParams struct {
	ID        pgtype.UUID     `json:"id"`
	TenantID  pgtype.UUID     `json:"tenant_id"`
	MetaValor decimal.Decimal `json:"meta_valor"`
}

func (q *Queries) UpdateMetaTicketMedio(ctx context.Context, arg UpdateMetaTicketMedioParams) (MetasTicketMedio, error) {
	row := q.db.QueryRow(ctx, updateMetaTicketMedio, arg.ID, arg.TenantID, arg.MetaValor)
	var i MetasTicketMedio
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MesAno,
		&i.MetaValor,
		&i.Tipo,
		&i.BarbeiroID,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}
