// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metas_barbeiro.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMetasBarbeiroByBarbeiro = `-- name: CountMetasBarbeiroByBarbeiro :one
SELECT COUNT(*) FROM metas_barbeiro
WHERE tenant_id = $1 AND barbeiro_id = $2
`

type CountMetasBarbeiroByBarbeiroParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	BarbeiroID pgtype.UUID `json:"barbeiro_id"`
}

func (q *Queries) CountMetasBarbeiroByBarbeiro(ctx context.Context, arg CountMetasBarbeiroByBarbeiroParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMetasBarbeiroByBarbeiro, arg.TenantID, arg.BarbeiroID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMetasBarbeiroByTenant = `-- name: CountMetasBarbeiroByTenant :one
SELECT COUNT(*) FROM metas_barbeiro
WHERE tenant_id = $1
`

func (q *Queries) CountMetasBarbeiroByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMetasBarbeiroByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMetaBarbeiro = `-- name: CreateMetaBarbeiro :one
INSERT INTO metas_barbeiro (
    tenant_id,
    barbeiro_id,
    mes_ano,
    meta_servicos_gerais,
    meta_servicos_extras,
    meta_produtos
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, barbeiro_id, mes_ano, meta_servicos_gerais, meta_servicos_extras, meta_produtos, criado_em, atualizado_em
`

type CreateMetaBarbeiroParams struct {
	TenantID           pgtype.UUID    `json:"tenant_id"`
	BarbeiroID         pgtype.UUID    `json:"barbeiro_id"`
	MesAno             string         `json:"mes_ano"`
	MetaServicosGerais pgtype.Numeric `json:"meta_servicos_gerais"`
	MetaServicosExtras pgtype.Numeric `json:"meta_servicos_extras"`
	MetaProdutos       pgtype.Numeric `json:"meta_produtos"`
}

func (q *Queries) CreateMetaBarbeiro(ctx context.Context, arg CreateMetaBarbeiroParams) (MetasBarbeiro, error) {
	row := q.db.QueryRow(ctx, createMetaBarbeiro,
		arg.TenantID,
		arg.BarbeiroID,
		arg.MesAno,
		arg.MetaServicosGerais,
		arg.MetaServicosExtras,
		arg.MetaProdutos,
	)
	var i MetasBarbeiro
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BarbeiroID,
		&i.MesAno,
		&i.MetaServicosGerais,
		&i.MetaServicosExtras,
		&i.MetaProdutos,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const deleteMetaBarbeiro = `-- name: DeleteMetaBarbeiro :exec
DELETE FROM metas_barbeiro
WHERE id = $1 AND tenant_id = $2
`

type DeleteMetaBarbeiroParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteMetaBarbeiro(ctx context.Context, arg DeleteMetaBarbeiroParams) error {
	_, err := q.db.Exec(ctx, deleteMetaBarbeiro, arg.ID, arg.TenantID)
	return err
}

const getMetaBarbeiroByID = `-- name: GetMetaBarbeiroByID :one
SELECT id, tenant_id, barbeiro_id, mes_ano, meta_servicos_gerais, meta_servicos_extras, meta_produtos, criado_em, atualizado_em FROM metas_barbeiro
WHERE id = $1 AND tenant_id = $2
`

type GetMetaBarbeiroByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetMetaBarbeiroByID(ctx context.Context, arg GetMetaBarbeiroByIDParams) (MetasBarbeiro, error) {
	row := q.db.QueryRow(ctx, getMetaBarbeiroByID, arg.ID, arg.TenantID)
	var i MetasBarbeiro
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BarbeiroID,
		&i.MesAno,
		&i.MetaServicosGerais,
		&i.MetaServicosExtras,
		&i.MetaProdutos,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getMetaBarbeiroByMesAno = `-- name: GetMetaBarbeiroByMesAno :one
SELECT id, tenant_id, barbeiro_id, mes_ano, meta_servicos_gerais, meta_servicos_extras, meta_produtos, criado_em, atualizado_em FROM metas_barbeiro
WHERE tenant_id = $1
  AND barbeiro_id = $2
  AND mes_ano = $3
`

type GetMetaBarbeiroByMesAnoParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	BarbeiroID pgtype.UUID `json:"barbeiro_id"`
	MesAno     string      `json:"mes_ano"`
}

func (q *Queries) GetMetaBarbeiroByMesAno(ctx context.Context, arg GetMetaBarbeiroByMesAnoParams) (MetasBarbeiro, error) {
	row := q.db.QueryRow(ctx, getMetaBarbeiroByMesAno, arg.TenantID, arg.BarbeiroID, arg.MesAno)
	var i MetasBarbeiro
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BarbeiroID,
		&i.MesAno,
		&i.MetaServicosGerais,
		&i.MetaServicosExtras,
		&i.MetaProdutos,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const listMetasBarbeiroByBarbeiro = `-- name: ListMetasBarbeiroByBarbeiro :many
SELECT id, tenant_id, barbeiro_id, mes_ano, meta_servicos_gerais, meta_servicos_extras, meta_produtos, criado_em, atualizado_em FROM metas_barbeiro
WHERE tenant_id = $1 AND barbeiro_id = $2
ORDER BY mes_ano DESC
LIMIT $3 OFFSET $4
`

type ListMetasBarbeiroByBarbeiroParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	BarbeiroID pgtype.UUID `json:"barbeiro_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListMetasBarbeiroByBarbeiro(ctx context.Context, arg ListMetasBarbeiroByBarbeiroParams) ([]MetasBarbeiro, error) {
	rows, err := q.db.Query(ctx, listMetasBarbeiroByBarbeiro,
		arg.TenantID,
		arg.BarbeiroID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetasBarbeiro{}
	for rows.Next() {
		var i MetasBarbeiro
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BarbeiroID,
			&i.MesAno,
			&i.MetaServicosGerais,
			&i.MetaServicosExtras,
			&i.MetaProdutos,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetasBarbeiroByMesAno = `-- name: ListMetasBarbeiroByMesAno :many
SELECT id, tenant_id, barbeiro_id, mes_ano, meta_servicos_gerais, meta_servicos_extras, meta_produtos, criado_em, atualizado_em FROM metas_barbeiro
WHERE tenant_id = $1 AND mes_ano = $2
ORDER BY barbeiro_id
`

type ListMetasBarbeiroByMesAnoParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	MesAno   string      `json:"mes_ano"`
}

func (q *Queries) ListMetasBarbeiroByMesAno(ctx context.Context, arg ListMetasBarbeiroByMesAnoParams) ([]MetasBarbeiro, error) {
	rows, err := q.db.Query(ctx, listMetasBarbeiroByMesAno, arg.TenantID, arg.MesAno)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetasBarbeiro{}
	for rows.Next() {
		var i MetasBarbeiro
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BarbeiroID,
			&i.MesAno,
			&i.MetaServicosGerais,
			&i.MetaServicosExtras,
			&i.MetaProdutos,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMetasBarbeiroByTenant = `-- name: ListMetasBarbeiroByTenant :many
SELECT id, tenant_id, barbeiro_id, mes_ano, meta_servicos_gerais, meta_servicos_extras, meta_produtos, criado_em, atualizado_em FROM metas_barbeiro
WHERE tenant_id = $1
ORDER BY mes_ano DESC, barbeiro_id
LIMIT $2 OFFSET $3
`

type ListMetasBarbeiroByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListMetasBarbeiroByTenant(ctx context.Context, arg ListMetasBarbeiroByTenantParams) ([]MetasBarbeiro, error) {
	rows, err := q.db.Query(ctx, listMetasBarbeiroByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetasBarbeiro{}
	for rows.Next() {
		var i MetasBarbeiro
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BarbeiroID,
			&i.MesAno,
			&i.MetaServicosGerais,
			&i.MetaServicosExtras,
			&i.MetaProdutos,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMetaBarbeiro = `-- name: UpdateMetaBarbeiro :one
UPDATE metas_barbeiro
SET
    meta_servicos_gerais = $3,
    meta_servicos_extras = $4,
    meta_produtos = $5,
    atualizado_em = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, barbeiro_id, mes_ano, meta_servicos_gerais, meta_servicos_extras, meta_produtos, criado_em, atualizado_em
`

type UpdateMetaBarbeiroParams struct {
	ID                 pgtype.UUID    `json:"id"`
	TenantID           pgtype.UUID    `json:"tenant_id"`
	MetaServicosGerais pgtype.Numeric `json:"meta_servicos_gerais"`
	MetaServicosExtras pgtype.Numeric `json:"meta_servicos_extras"`
	MetaProdutos       pgtype.Numeric `json:"meta_produtos"`
}

func (q *Queries) UpdateMetaBarbeiro(ctx context.Context, arg UpdateMetaBarbeiroParams) (MetasBarbeiro, error) {
	row := q.db.QueryRow(ctx, updateMetaBarbeiro,
		arg.ID,
		arg.TenantID,
		arg.MetaServicosGerais,
		arg.MetaServicosExtras,
		arg.MetaProdutos,
	)
	var i MetasBarbeiro
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BarbeiroID,
		&i.MesAno,
		&i.MetaServicosGerais,
		&i.MetaServicosExtras,
		&i.MetaProdutos,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}
