// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

// Compensações bancárias com D+ para fluxo de caixa compensado
type CompensacoesBancaria struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ReceitaID       pgtype.UUID        `json:"receita_id"`
	DataTransacao   pgtype.Date        `json:"data_transacao"`
	DataCompensacao pgtype.Date        `json:"data_compensacao"`
	DataCompensado  pgtype.Date        `json:"data_compensado"`
	ValorBruto      decimal.Decimal    `json:"valor_bruto"`
	TaxaPercentual  pgtype.Numeric     `json:"taxa_percentual"`
	TaxaFixa        pgtype.Numeric     `json:"taxa_fixa"`
	ValorLiquido    decimal.Decimal    `json:"valor_liquido"`
	MeioPagamentoID pgtype.UUID        `json:"meio_pagamento_id"`
	DMais           int32              `json:"d_mais"`
	Status          *string            `json:"status"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm    pgtype.Timestamptz `json:"atualizado_em"`
}

// Contas a pagar com suporte a recorrência e notificações
type ContasAPagar struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	Descricao      string             `json:"descricao"`
	CategoriaID    pgtype.UUID        `json:"categoria_id"`
	Fornecedor     *string            `json:"fornecedor"`
	Valor          decimal.Decimal    `json:"valor"`
	Tipo           *string            `json:"tipo"`
	Recorrente     *bool              `json:"recorrente"`
	Periodicidade  *string            `json:"periodicidade"`
	DataVencimento pgtype.Date        `json:"data_vencimento"`
	DataPagamento  pgtype.Date        `json:"data_pagamento"`
	Status         *string            `json:"status"`
	ComprovanteUrl *string            `json:"comprovante_url"`
	PixCode        *string            `json:"pix_code"`
	Observacoes    *string            `json:"observacoes"`
	CriadoEm       pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm   pgtype.Timestamptz `json:"atualizado_em"`
}

// Contas a receber de assinaturas e serviços com alertas de inadimplência
type ContasAReceber struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	Origem          *string            `json:"origem"`
	AssinaturaID    pgtype.UUID        `json:"assinatura_id"`
	ServicoID       pgtype.UUID        `json:"servico_id"`
	Descricao       string             `json:"descricao"`
	Valor           decimal.Decimal    `json:"valor"`
	ValorPago       pgtype.Numeric     `json:"valor_pago"`
	DataVencimento  pgtype.Date        `json:"data_vencimento"`
	DataRecebimento pgtype.Date        `json:"data_recebimento"`
	Status          *string            `json:"status"`
	Observacoes     *string            `json:"observacoes"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm    pgtype.Timestamptz `json:"atualizado_em"`
}

// Demonstrativo de Resultado do Exercício mensal por tenant
type DreMensal struct {
	ID                   pgtype.UUID        `json:"id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	MesAno               string             `json:"mes_ano"`
	ReceitaServicos      pgtype.Numeric     `json:"receita_servicos"`
	ReceitaProdutos      pgtype.Numeric     `json:"receita_produtos"`
	ReceitaPlanos        pgtype.Numeric     `json:"receita_planos"`
	ReceitaTotal         pgtype.Numeric     `json:"receita_total"`
	CustoComissoes       pgtype.Numeric     `json:"custo_comissoes"`
	CustoInsumos         pgtype.Numeric     `json:"custo_insumos"`
	CustoVariavelTotal   pgtype.Numeric     `json:"custo_variavel_total"`
	DespesaFixa          pgtype.Numeric     `json:"despesa_fixa"`
	DespesaVariavel      pgtype.Numeric     `json:"despesa_variavel"`
	DespesaTotal         pgtype.Numeric     `json:"despesa_total"`
	ResultadoBruto       pgtype.Numeric     `json:"resultado_bruto"`
	ResultadoOperacional pgtype.Numeric     `json:"resultado_operacional"`
	MargemBruta          pgtype.Numeric     `json:"margem_bruta"`
	MargemOperacional    pgtype.Numeric     `json:"margem_operacional"`
	LucroLiquido         pgtype.Numeric     `json:"lucro_liquido"`
	ProcessadoEm         pgtype.Timestamptz `json:"processado_em"`
	CriadoEm             pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm         pgtype.Timestamptz `json:"atualizado_em"`
}

// Fluxo de caixa diário com previsões e compensações bancárias
type FluxoCaixaDiario struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	Data                pgtype.Date        `json:"data"`
	SaldoInicial        pgtype.Numeric     `json:"saldo_inicial"`
	SaldoFinal          pgtype.Numeric     `json:"saldo_final"`
	EntradasConfirmadas pgtype.Numeric     `json:"entradas_confirmadas"`
	EntradasPrevistas   pgtype.Numeric     `json:"entradas_previstas"`
	SaidasPagas         pgtype.Numeric     `json:"saidas_pagas"`
	SaidasPrevistas     pgtype.Numeric     `json:"saidas_previstas"`
	ProcessadoEm        pgtype.Timestamptz `json:"processado_em"`
	CriadoEm            pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm        pgtype.Timestamptz `json:"atualizado_em"`
}

// Metas individuais por barbeiro (serviços gerais, extras, produtos)
type MetasBarbeiro struct {
	ID                 pgtype.UUID        `json:"id"`
	TenantID           pgtype.UUID        `json:"tenant_id"`
	BarbeiroID         pgtype.UUID        `json:"barbeiro_id"`
	MesAno             string             `json:"mes_ano"`
	MetaServicosGerais pgtype.Numeric     `json:"meta_servicos_gerais"`
	MetaServicosExtras pgtype.Numeric     `json:"meta_servicos_extras"`
	MetaProdutos       pgtype.Numeric     `json:"meta_produtos"`
	CriadoEm           pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm       pgtype.Timestamptz `json:"atualizado_em"`
}

// Metas de faturamento mensal por tenant
type MetasMensai struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	MesAno          string             `json:"mes_ano"`
	MetaFaturamento decimal.Decimal    `json:"meta_faturamento"`
	Origem          *string            `json:"origem"`
	Status          *string            `json:"status"`
	CriadoPor       pgtype.UUID        `json:"criado_por"`
	CriadoEm        pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm    pgtype.Timestamptz `json:"atualizado_em"`
}

// Metas de ticket médio (geral ou por barbeiro)
type MetasTicketMedio struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	MesAno       string             `json:"mes_ano"`
	MetaValor    decimal.Decimal    `json:"meta_valor"`
	Tipo         *string            `json:"tipo"`
	BarbeiroID   pgtype.UUID        `json:"barbeiro_id"`
	CriadoEm     pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm pgtype.Timestamptz `json:"atualizado_em"`
}

// Configurações de precificação padrão por tenant (margem, markup, impostos, comissões)
type PrecificacaoConfig struct {
	ID                        pgtype.UUID        `json:"id"`
	TenantID                  pgtype.UUID        `json:"tenant_id"`
	MargemDesejada            pgtype.Numeric     `json:"margem_desejada"`
	MarkupAlvo                pgtype.Numeric     `json:"markup_alvo"`
	ImpostoPercentual         pgtype.Numeric     `json:"imposto_percentual"`
	ComissaoPercentualDefault pgtype.Numeric     `json:"comissao_percentual_default"`
	CriadoEm                  pgtype.Timestamptz `json:"criado_em"`
	AtualizadoEm              pgtype.Timestamptz `json:"atualizado_em"`
}

// Histórico de simulações de precificação com parâmetros e resultados
type PrecificacaoSimulaco struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	ItemID              pgtype.UUID        `json:"item_id"`
	TipoItem            *string            `json:"tipo_item"`
	CustoMateriais      pgtype.Numeric     `json:"custo_materiais"`
	CustoMaoDeObra      pgtype.Numeric     `json:"custo_mao_de_obra"`
	CustoTotal          pgtype.Numeric     `json:"custo_total"`
	MargemDesejada      decimal.Decimal    `json:"margem_desejada"`
	ComissaoPercentual  decimal.Decimal    `json:"comissao_percentual"`
	ImpostoPercentual   decimal.Decimal    `json:"imposto_percentual"`
	PrecoSugerido       decimal.Decimal    `json:"preco_sugerido"`
	PrecoAtual          pgtype.Numeric     `json:"preco_atual"`
	DiferencaPercentual pgtype.Numeric     `json:"diferenca_percentual"`
	LucroEstimado       pgtype.Numeric     `json:"lucro_estimado"`
	MargemFinal         pgtype.Numeric     `json:"margem_final"`
	CustoInsumos        pgtype.Numeric     `json:"custo_insumos"`
	MarkupAplicado      pgtype.Numeric     `json:"markup_aplicado"`
	MargemResultante    pgtype.Numeric     `json:"margem_resultante"`
	ParametrosJson      []byte             `json:"parametros_json"`
	CriadoPor           pgtype.UUID        `json:"criado_por"`
	CriadoEm            pgtype.Timestamptz `json:"criado_em"`
}

type UserPreference struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	AnalyticsEnabled     bool               `json:"analytics_enabled"`
	ErrorTrackingEnabled bool               `json:"error_tracking_enabled"`
	MarketingEnabled     bool               `json:"marketing_enabled"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
