// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: precificacao_simulacoes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countSimulacoesByItem = `-- name: CountSimulacoesByItem :one
SELECT COUNT(*) FROM precificacao_simulacoes
WHERE tenant_id = $1 AND item_id = $2
`

type CountSimulacoesByItemParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ItemID   pgtype.UUID `json:"item_id"`
}

func (q *Queries) CountSimulacoesByItem(ctx context.Context, arg CountSimulacoesByItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSimulacoesByItem, arg.TenantID, arg.ItemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSimulacoesByTenant = `-- name: CountSimulacoesByTenant :one
SELECT COUNT(*) FROM precificacao_simulacoes
WHERE tenant_id = $1
`

func (q *Queries) CountSimulacoesByTenant(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSimulacoesByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPrecificacaoSimulacao = `-- name: CreatePrecificacaoSimulacao :one
INSERT INTO precificacao_simulacoes (
    tenant_id,
    item_id,
    tipo_item,
    custo_materiais,
    custo_mao_de_obra,
    custo_total,
    margem_desejada,
    comissao_percentual,
    imposto_percentual,
    preco_sugerido,
    preco_atual,
    diferenca_percentual,
    lucro_estimado,
    margem_final,
    parametros_json,
    criado_por
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
) RETURNING id, tenant_id, item_id, tipo_item, custo_materiais, custo_mao_de_obra, custo_total, margem_desejada, comissao_percentual, imposto_percentual, preco_sugerido, preco_atual, diferenca_percentual, lucro_estimado, margem_final, custo_insumos, markup_aplicado, margem_resultante, parametros_json, criado_por, criado_em
`

type CreatePrecificacaoSimulacaoParams struct {
	TenantID            pgtype.UUID     `json:"tenant_id"`
	ItemID              pgtype.UUID     `json:"item_id"`
	TipoItem            *string         `json:"tipo_item"`
	CustoMateriais      pgtype.Numeric  `json:"custo_materiais"`
	CustoMaoDeObra      pgtype.Numeric  `json:"custo_mao_de_obra"`
	CustoTotal          pgtype.Numeric  `json:"custo_total"`
	MargemDesejada      decimal.Decimal `json:"margem_desejada"`
	ComissaoPercentual  decimal.Decimal `json:"comissao_percentual"`
	ImpostoPercentual   decimal.Decimal `json:"imposto_percentual"`
	PrecoSugerido       decimal.Decimal `json:"preco_sugerido"`
	PrecoAtual          pgtype.Numeric  `json:"preco_atual"`
	DiferencaPercentual pgtype.Numeric  `json:"diferenca_percentual"`
	LucroEstimado       pgtype.Numeric  `json:"lucro_estimado"`
	MargemFinal         pgtype.Numeric  `json:"margem_final"`
	ParametrosJson      []byte          `json:"parametros_json"`
	CriadoPor           pgtype.UUID     `json:"criado_por"`
}

func (q *Queries) CreatePrecificacaoSimulacao(ctx context.Context, arg CreatePrecificacaoSimulacaoParams) (PrecificacaoSimulaco, error) {
	row := q.db.QueryRow(ctx, createPrecificacaoSimulacao,
		arg.TenantID,
		arg.ItemID,
		arg.TipoItem,
		arg.CustoMateriais,
		arg.CustoMaoDeObra,
		arg.CustoTotal,
		arg.MargemDesejada,
		arg.ComissaoPercentual,
		arg.ImpostoPercentual,
		arg.PrecoSugerido,
		arg.PrecoAtual,
		arg.DiferencaPercentual,
		arg.LucroEstimado,
		arg.MargemFinal,
		arg.ParametrosJson,
		arg.CriadoPor,
	)
	var i PrecificacaoSimulaco
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ItemID,
		&i.TipoItem,
		&i.CustoMateriais,
		&i.CustoMaoDeObra,
		&i.CustoTotal,
		&i.MargemDesejada,
		&i.ComissaoPercentual,
		&i.ImpostoPercentual,
		&i.PrecoSugerido,
		&i.PrecoAtual,
		&i.DiferencaPercentual,
		&i.LucroEstimado,
		&i.MargemFinal,
		&i.CustoInsumos,
		&i.MarkupAplicado,
		&i.MargemResultante,
		&i.ParametrosJson,
		&i.CriadoPor,
		&i.CriadoEm,
	)
	return i, err
}

const deletePrecificacaoSimulacao = `-- name: DeletePrecificacaoSimulacao :exec
DELETE FROM precificacao_simulacoes
WHERE id = $1 AND tenant_id = $2
`

type DeletePrecificacaoSimulacaoParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeletePrecificacaoSimulacao(ctx context.Context, arg DeletePrecificacaoSimulacaoParams) error {
	_, err := q.db.Exec(ctx, deletePrecificacaoSimulacao, arg.ID, arg.TenantID)
	return err
}

const getPrecificacaoSimulacaoByID = `-- name: GetPrecificacaoSimulacaoByID :one
SELECT id, tenant_id, item_id, tipo_item, custo_materiais, custo_mao_de_obra, custo_total, margem_desejada, comissao_percentual, imposto_percentual, preco_sugerido, preco_atual, diferenca_percentual, lucro_estimado, margem_final, custo_insumos, markup_aplicado, margem_resultante, parametros_json, criado_por, criado_em FROM precificacao_simulacoes
WHERE id = $1 AND tenant_id = $2
`

type GetPrecificacaoSimulacaoByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetPrecificacaoSimulacaoByID(ctx context.Context, arg GetPrecificacaoSimulacaoByIDParams) (PrecificacaoSimulaco, error) {
	row := q.db.QueryRow(ctx, getPrecificacaoSimulacaoByID, arg.ID, arg.TenantID)
	var i PrecificacaoSimulaco
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ItemID,
		&i.TipoItem,
		&i.CustoMateriais,
		&i.CustoMaoDeObra,
		&i.CustoTotal,
		&i.MargemDesejada,
		&i.ComissaoPercentual,
		&i.ImpostoPercentual,
		&i.PrecoSugerido,
		&i.PrecoAtual,
		&i.DiferencaPercentual,
		&i.LucroEstimado,
		&i.MargemFinal,
		&i.CustoInsumos,
		&i.MarkupAplicado,
		&i.MargemResultante,
		&i.ParametrosJson,
		&i.CriadoPor,
		&i.CriadoEm,
	)
	return i, err
}

const getUltimaSimulacaoByItem = `-- name: GetUltimaSimulacaoByItem :one
SELECT id, tenant_id, item_id, tipo_item, custo_materiais, custo_mao_de_obra, custo_total, margem_desejada, comissao_percentual, imposto_percentual, preco_sugerido, preco_atual, diferenca_percentual, lucro_estimado, margem_final, custo_insumos, markup_aplicado, margem_resultante, parametros_json, criado_por, criado_em FROM precificacao_simulacoes
WHERE tenant_id = $1 AND item_id = $2
ORDER BY criado_em DESC
LIMIT 1
`

type GetUltimaSimulacaoByItemParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ItemID   pgtype.UUID `json:"item_id"`
}

func (q *Queries) GetUltimaSimulacaoByItem(ctx context.Context, arg GetUltimaSimulacaoByItemParams) (PrecificacaoSimulaco, error) {
	row := q.db.QueryRow(ctx, getUltimaSimulacaoByItem, arg.TenantID, arg.ItemID)
	var i PrecificacaoSimulaco
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ItemID,
		&i.TipoItem,
		&i.CustoMateriais,
		&i.CustoMaoDeObra,
		&i.CustoTotal,
		&i.MargemDesejada,
		&i.ComissaoPercentual,
		&i.ImpostoPercentual,
		&i.PrecoSugerido,
		&i.PrecoAtual,
		&i.DiferencaPercentual,
		&i.LucroEstimado,
		&i.MargemFinal,
		&i.CustoInsumos,
		&i.MarkupAplicado,
		&i.MargemResultante,
		&i.ParametrosJson,
		&i.CriadoPor,
		&i.CriadoEm,
	)
	return i, err
}

const listSimulacoesByItem = `-- name: ListSimulacoesByItem :many
SELECT id, tenant_id, item_id, tipo_item, custo_materiais, custo_mao_de_obra, custo_total, margem_desejada, comissao_percentual, imposto_percentual, preco_sugerido, preco_atual, diferenca_percentual, lucro_estimado, margem_final, custo_insumos, markup_aplicado, margem_resultante, parametros_json, criado_por, criado_em FROM precificacao_simulacoes
WHERE tenant_id = $1 AND item_id = $2
ORDER BY criado_em DESC
LIMIT $3 OFFSET $4
`

type ListSimulacoesByItemParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ItemID   pgtype.UUID `json:"item_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListSimulacoesByItem(ctx context.Context, arg ListSimulacoesByItemParams) ([]PrecificacaoSimulaco, error) {
	rows, err := q.db.Query(ctx, listSimulacoesByItem,
		arg.TenantID,
		arg.ItemID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrecificacaoSimulaco{}
	for rows.Next() {
		var i PrecificacaoSimulaco
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ItemID,
			&i.TipoItem,
			&i.CustoMateriais,
			&i.CustoMaoDeObra,
			&i.CustoTotal,
			&i.MargemDesejada,
			&i.ComissaoPercentual,
			&i.ImpostoPercentual,
			&i.PrecoSugerido,
			&i.PrecoAtual,
			&i.DiferencaPercentual,
			&i.LucroEstimado,
			&i.MargemFinal,
			&i.CustoInsumos,
			&i.MarkupAplicado,
			&i.MargemResultante,
			&i.ParametrosJson,
			&i.CriadoPor,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimulacoesByTenant = `-- name: ListSimulacoesByTenant :many
SELECT id, tenant_id, item_id, tipo_item, custo_materiais, custo_mao_de_obra, custo_total, margem_desejada, comissao_percentual, imposto_percentual, preco_sugerido, preco_atual, diferenca_percentual, lucro_estimado, margem_final, custo_insumos, markup_aplicado, margem_resultante, parametros_json, criado_por, criado_em FROM precificacao_simulacoes
WHERE tenant_id = $1
ORDER BY criado_em DESC
LIMIT $2 OFFSET $3
`

type ListSimulacoesByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListSimulacoesByTenant(ctx context.Context, arg ListSimulacoesByTenantParams) ([]PrecificacaoSimulaco, error) {
	rows, err := q.db.Query(ctx, listSimulacoesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrecificacaoSimulaco{}
	for rows.Next() {
		var i PrecificacaoSimulaco
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ItemID,
			&i.TipoItem,
			&i.CustoMateriais,
			&i.CustoMaoDeObra,
			&i.CustoTotal,
			&i.MargemDesejada,
			&i.ComissaoPercentual,
			&i.ImpostoPercentual,
			&i.PrecoSugerido,
			&i.PrecoAtual,
			&i.DiferencaPercentual,
			&i.LucroEstimado,
			&i.MargemFinal,
			&i.CustoInsumos,
			&i.MarkupAplicado,
			&i.MargemResultante,
			&i.ParametrosJson,
			&i.CriadoPor,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimulacoesByTipoItem = `-- name: ListSimulacoesByTipoItem :many
SELECT id, tenant_id, item_id, tipo_item, custo_materiais, custo_mao_de_obra, custo_total, margem_desejada, comissao_percentual, imposto_percentual, preco_sugerido, preco_atual, diferenca_percentual, lucro_estimado, margem_final, custo_insumos, markup_aplicado, margem_resultante, parametros_json, criado_por, criado_em FROM precificacao_simulacoes
WHERE tenant_id = $1 AND tipo_item = $2
ORDER BY criado_em DESC
LIMIT $3 OFFSET $4
`

type ListSimulacoesByTipoItemParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	TipoItem *string     `json:"tipo_item"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListSimulacoesByTipoItem(ctx context.Context, arg ListSimulacoesByTipoItemParams) ([]PrecificacaoSimulaco, error) {
	rows, err := q.db.Query(ctx, listSimulacoesByTipoItem,
		arg.TenantID,
		arg.TipoItem,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrecificacaoSimulaco{}
	for rows.Next() {
		var i PrecificacaoSimulaco
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ItemID,
			&i.TipoItem,
			&i.CustoMateriais,
			&i.CustoMaoDeObra,
			&i.CustoTotal,
			&i.MargemDesejada,
			&i.ComissaoPercentual,
			&i.ImpostoPercentual,
			&i.PrecoSugerido,
			&i.PrecoAtual,
			&i.DiferencaPercentual,
			&i.LucroEstimado,
			&i.MargemFinal,
			&i.CustoInsumos,
			&i.MarkupAplicado,
			&i.MargemResultante,
			&i.ParametrosJson,
			&i.CriadoPor,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSimulacoesByUsuario = `-- name: ListSimulacoesByUsuario :many
SELECT id, tenant_id, item_id, tipo_item, custo_materiais, custo_mao_de_obra, custo_total, margem_desejada, comissao_percentual, imposto_percentual, preco_sugerido, preco_atual, diferenca_percentual, lucro_estimado, margem_final, custo_insumos, markup_aplicado, margem_resultante, parametros_json, criado_por, criado_em FROM precificacao_simulacoes
WHERE tenant_id = $1 AND criado_por = $2
ORDER BY criado_em DESC
LIMIT $3 OFFSET $4
`

type ListSimulacoesByUsuarioParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	CriadoPor pgtype.UUID `json:"criado_por"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListSimulacoesByUsuario(ctx context.Context, arg ListSimulacoesByUsuarioParams) ([]PrecificacaoSimulaco, error) {
	rows, err := q.db.Query(ctx, listSimulacoesByUsuario,
		arg.TenantID,
		arg.CriadoPor,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrecificacaoSimulaco{}
	for rows.Next() {
		var i PrecificacaoSimulaco
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ItemID,
			&i.TipoItem,
			&i.CustoMateriais,
			&i.CustoMaoDeObra,
			&i.CustoTotal,
			&i.MargemDesejada,
			&i.ComissaoPercentual,
			&i.ImpostoPercentual,
			&i.PrecoSugerido,
			&i.PrecoAtual,
			&i.DiferencaPercentual,
			&i.LucroEstimado,
			&i.MargemFinal,
			&i.CustoInsumos,
			&i.MarkupAplicado,
			&i.MargemResultante,
			&i.ParametrosJson,
			&i.CriadoPor,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
