// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: precificacao_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPrecificacaoConfig = `-- name: CreatePrecificacaoConfig :one
INSERT INTO precificacao_config (
    tenant_id,
    margem_desejada,
    markup_alvo,
    imposto_percentual,
    comissao_percentual_default
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, tenant_id, margem_desejada, markup_alvo, imposto_percentual, comissao_percentual_default, criado_em, atualizado_em
`

type CreatePrecificacaoConfigParams struct {
	TenantID                  pgtype.UUID    `json:"tenant_id"`
	MargemDesejada            pgtype.Numeric `json:"margem_desejada"`
	MarkupAlvo                pgtype.Numeric `json:"markup_alvo"`
	ImpostoPercentual         pgtype.Numeric `json:"imposto_percentual"`
	ComissaoPercentualDefault pgtype.Numeric `json:"comissao_percentual_default"`
}

func (q *Queries) CreatePrecificacaoConfig(ctx context.Context, arg CreatePrecificacaoConfigParams) (PrecificacaoConfig, error) {
	row := q.db.QueryRow(ctx, createPrecificacaoConfig,
		arg.TenantID,
		arg.MargemDesejada,
		arg.MarkupAlvo,
		arg.ImpostoPercentual,
		arg.ComissaoPercentualDefault,
	)
	var i PrecificacaoConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MargemDesejada,
		&i.MarkupAlvo,
		&i.ImpostoPercentual,
		&i.ComissaoPercentualDefault,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const deletePrecificacaoConfig = `-- name: DeletePrecificacaoConfig :exec
DELETE FROM precificacao_config
WHERE id = $1 AND tenant_id = $2
`

type DeletePrecificacaoConfigParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeletePrecificacaoConfig(ctx context.Context, arg DeletePrecificacaoConfigParams) error {
	_, err := q.db.Exec(ctx, deletePrecificacaoConfig, arg.ID, arg.TenantID)
	return err
}

const getPrecificacaoConfigByID = `-- name: GetPrecificacaoConfigByID :one
SELECT id, tenant_id, margem_desejada, markup_alvo, imposto_percentual, comissao_percentual_default, criado_em, atualizado_em FROM precificacao_config
WHERE id = $1 AND tenant_id = $2
`

type GetPrecificacaoConfigByIDParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetPrecificacaoConfigByID(ctx context.Context, arg GetPrecificacaoConfigByIDParams) (PrecificacaoConfig, error) {
	row := q.db.QueryRow(ctx, getPrecificacaoConfigByID, arg.ID, arg.TenantID)
	var i PrecificacaoConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MargemDesejada,
		&i.MarkupAlvo,
		&i.ImpostoPercentual,
		&i.ComissaoPercentualDefault,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getPrecificacaoConfigByTenant = `-- name: GetPrecificacaoConfigByTenant :one
SELECT id, tenant_id, margem_desejada, markup_alvo, imposto_percentual, comissao_percentual_default, criado_em, atualizado_em FROM precificacao_config
WHERE tenant_id = $1
`

func (q *Queries) GetPrecificacaoConfigByTenant(ctx context.Context, tenantID pgtype.UUID) (PrecificacaoConfig, error) {
	row := q.db.QueryRow(ctx, getPrecificacaoConfigByTenant, tenantID)
	var i PrecificacaoConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MargemDesejada,
		&i.MarkupAlvo,
		&i.ImpostoPercentual,
		&i.ComissaoPercentualDefault,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const updatePrecificacaoConfig = `-- name: UpdatePrecificacaoConfig :one
UPDATE precificacao_config
SET
    margem_desejada = $3,
    markup_alvo = $4,
    imposto_percentual = $5,
    comissao_percentual_default = $6,
    atualizado_em = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, margem_desejada, markup_alvo, imposto_percentual, comissao_percentual_default, criado_em, atualizado_em
`

type UpdatePrecificacaoConfigParams struct {
	ID                        pgtype.UUID    `json:"id"`
	TenantID                  pgtype.UUID    `json:"tenant_id"`
	MargemDesejada            pgtype.Numeric `json:"margem_desejada"`
	MarkupAlvo                pgtype.Numeric `json:"markup_alvo"`
	ImpostoPercentual         pgtype.Numeric `json:"imposto_percentual"`
	ComissaoPercentualDefault pgtype.Numeric `json:"comissao_percentual_default"`
}

func (q *Queries) UpdatePrecificacaoConfig(ctx context.Context, arg UpdatePrecificacaoConfigParams) (PrecificacaoConfig, error) {
	row := q.db.QueryRow(ctx, updatePrecificacaoConfig,
		arg.ID,
		arg.TenantID,
		arg.MargemDesejada,
		arg.MarkupAlvo,
		arg.ImpostoPercentual,
		arg.ComissaoPercentualDefault,
	)
	var i PrecificacaoConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MargemDesejada,
		&i.MarkupAlvo,
		&i.ImpostoPercentual,
		&i.ComissaoPercentualDefault,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}
