// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_preferences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserPreferences = `-- name: CountUserPreferences :one
SELECT COUNT(*) FROM user_preferences
`

func (q *Queries) CountUserPreferences(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUserPreferences)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserPreferences = `-- name: CreateUserPreferences :one
INSERT INTO user_preferences (
    user_id,
    analytics_enabled,
    error_tracking_enabled,
    marketing_enabled
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, analytics_enabled, error_tracking_enabled, marketing_enabled, created_at, updated_at
`

type CreateUserPreferencesParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	AnalyticsEnabled     bool        `json:"analytics_enabled"`
	ErrorTrackingEnabled bool        `json:"error_tracking_enabled"`
	MarketingEnabled     bool        `json:"marketing_enabled"`
}

func (q *Queries) CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, createUserPreferences,
		arg.UserID,
		arg.AnalyticsEnabled,
		arg.ErrorTrackingEnabled,
		arg.MarketingEnabled,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnalyticsEnabled,
		&i.ErrorTrackingEnabled,
		&i.MarketingEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserPreferences = `-- name: DeleteUserPreferences :exec
DELETE FROM user_preferences
WHERE user_id = $1
`

func (q *Queries) DeleteUserPreferences(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserPreferences, userID)
	return err
}

const getUserPreferencesByID = `-- name: GetUserPreferencesByID :one
SELECT id, user_id, analytics_enabled, error_tracking_enabled, marketing_enabled, created_at, updated_at FROM user_preferences
WHERE id = $1
`

func (q *Queries) GetUserPreferencesByID(ctx context.Context, id pgtype.UUID) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferencesByID, id)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnalyticsEnabled,
		&i.ErrorTrackingEnabled,
		&i.MarketingEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPreferencesByUserID = `-- name: GetUserPreferencesByUserID :one
SELECT id, user_id, analytics_enabled, error_tracking_enabled, marketing_enabled, created_at, updated_at FROM user_preferences
WHERE user_id = $1
`

func (q *Queries) GetUserPreferencesByUserID(ctx context.Context, userID pgtype.UUID) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferencesByUserID, userID)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnalyticsEnabled,
		&i.ErrorTrackingEnabled,
		&i.MarketingEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersWithAnalyticsEnabled = `-- name: ListUsersWithAnalyticsEnabled :many
SELECT user_id FROM user_preferences
WHERE analytics_enabled = true
`

func (q *Queries) ListUsersWithAnalyticsEnabled(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUsersWithAnalyticsEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithMarketingEnabled = `-- name: ListUsersWithMarketingEnabled :many
SELECT user_id FROM user_preferences
WHERE marketing_enabled = true
`

func (q *Queries) ListUsersWithMarketingEnabled(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listUsersWithMarketingEnabled)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPreferences = `-- name: UpdateUserPreferences :one
UPDATE user_preferences
SET
    analytics_enabled = $2,
    error_tracking_enabled = $3,
    marketing_enabled = $4,
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, analytics_enabled, error_tracking_enabled, marketing_enabled, created_at, updated_at
`

type UpdateUserPreferencesParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	AnalyticsEnabled     bool        `json:"analytics_enabled"`
	ErrorTrackingEnabled bool        `json:"error_tracking_enabled"`
	MarketingEnabled     bool        `json:"marketing_enabled"`
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, updateUserPreferences,
		arg.UserID,
		arg.AnalyticsEnabled,
		arg.ErrorTrackingEnabled,
		arg.MarketingEnabled,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AnalyticsEnabled,
		&i.ErrorTrackingEnabled,
		&i.MarketingEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
